name: Steps Type 2

on:
  workflow_dispatch:


jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
    - run: "echo Hello from an inline bash script in a Github Action Workflow!"

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
    - run: print("Hello from an inline python script in a Github Action Workflow!")
      shell: python

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
      with:
        who-to-greet: "from an actions from Github Actions marketplace"
