name: "Action1"
on:
  workflow_dispatch:
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout repository"
          id: checkout
          run: echo foo="bar">> $GITHUB_OUTPUT

        - name: "Run a one-line script"
          run: echo ${ { steps.checkout.outputs.foo } }
    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: "Checkout repository"
          id: checkout
          run: echo foo="bar2">> $GITHUB_OUTPUT

        - name: "Run a one-line script"
          run: echo from job2 ${ { steps.checkout.outputs.foo } }
               echo from job1 ${ { needs.job1.outputs.foo } }
