name: "Action1"
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.checkout.outputs.foo }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      - name: "Set output"
        id: checkout
        run: echo "foo=bar" >> $GITHUB_OUTPUT
  
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      - name: "Set output in job2"
        id: checkout2
        run: echo "foo=bar2" >> $GITHUB_OUTPUT
      
      - name: "Run a one-line script"
        run: |
          echo "from job2: ${{ steps.checkout2.outputs.foo }}"
          echo "from job1: ${{ needs.job1.outputs.foo }}"
