name: 3 steps
on: workflow_dispatch
jobs:
    run-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello World"
    run-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("Hello World")
              shell: python
    run-git-action:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/hello-world-javascript-action@v1
              with:
                   who-to-greet: "Hello"