name: stepbystep
on: workflow_dispatch
jobs:
    step1:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "run step 1"
    step2:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "run step 2"
    step3:
        runs-on: ubuntu-24.04
        needs: [step1, step2]
        steps:
            - run: echo "run step 3"
    step4:
        runs-on: ubuntu-24.04
        needs: [step1, step3]
        steps:
            - run: echo "run step 4"