name: pull request 1
on:
    push:
        branches:
            - 'example-branch/*'
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - '!03-core-features/filters/excluded-file.txt'
            - '03-core-features/filters/included-file.md'
    workflow_dispatch:
jobs:
    echo-hello:
        runs-on: ubuntu-24.04
        steps:
            - name: hello
              run: cat "$GITHUB_EVENT_PATH"
